"""
Django settings for bokuto_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
import sys
from pathlib import Path
import oracledb
from dotenv import load_dotenv

# Activar el modo "Thick" de oracledb para leer el Wallet de Oracle
#oracledb.init_oracle_client()

# Reemplazar cx_Oracle por oracledb para compatibilidad con Django
sys.modules["cx_Oracle"] = oracledb

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno del archivo .env
load_dotenv()

# Decirle a Oracle dónde está la carpeta con los archivos del Wallet
os.environ['TNS_ADMIN'] = os.path.join(BASE_DIR, 'wallet')

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-py5fybal$$#ty@67^ffe70lcr(^v068wefqufu9#i-&9+n*40g'
DEBUG = True
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías externas
    'rest_framework',
    'corsheaders',
    'storages',  # Añadido para AWS S3
    
    # Apps locales
    'logistica',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bokuto_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bokuto_backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'bokutodatabase_high', 
        'USER': 'ADMIN',
        'PASSWORD': 'Colita02551!',
        'OPTIONS': {
            'config_dir': str(BASE_DIR / 'wallet'),
            'wallet_location': str(BASE_DIR / 'wallet'),
            'wallet_password': 'Colita02551!', 
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Email
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

CORS_ALLOW_ALL_ORIGINS = True
AUTH_USER_MODEL = 'logistica.Usuario'

# ==============================================================================
# CONFIGURACIÓN DE AWS S3 PARA IMÁGENES
# ==============================================================================
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True

# Nueva configuración de almacenamiento para versiones recientes de Django
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}