# Generated by Django 6.1.1 on 2026-09-24 00:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import logistica.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(help_text='RUT con formato estricto: 1.111.111-1', max_length=12, unique=True, validators=[logistica.models.validar_rut_estricto])),
                ('rol', models.CharField(choices=[('BODEGUERO', 'Bodeguero'), ('OPERADOR_SALA', 'Operador de Sala'), ('ADMINISTRADOR', 'Administrador')], default='OPERADOR_SALA', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_logistica_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_logistica_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.PositiveIntegerField(help_text='Stock con el que ingresó el lote')),
                ('cantidad_actual', models.PositiveIntegerField(help_text='Stock disponible real')),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('ubicacion', models.CharField(choices=[('BODEGA', 'Bodega Principal'), ('SALA', 'Sala de Ventas')], default='BODEGA', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('operario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento'), ('ROTURA', 'Rotura o Daño'), ('ROBO', 'Robo o Extravío'), ('ERROR_INVENTARIO', 'Ajuste por Error de Inventario')], max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='logistica.lotestock')),
                ('operario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('origen', models.CharField(help_text='Ej: Bodega Central', max_length=50)),
                ('destino', models.CharField(help_text='Ej: Pasillo 4', max_length=50)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='logistica.lotestock')),
                ('operario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_barras', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_minimo', models.PositiveIntegerField(default=10, help_text='Umbral para alerta en panel admin')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de referencia del producto', null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='logistica.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='lotestock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='logistica.producto'),
        ),
    ]
